version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - mcc-network
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - mcc-network
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9093:9093"
    healthcheck:
      test: zookeeper-shell zookeeper:2181 ls /brokers/ids | grep -F [ | grep [0-9] || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    hostname: kafdrop
    container_name: kafdrop
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - mcc-network
    ports:
      - "9000:9000"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:5.0.6
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - mcc-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 15
    ports:
      - 27017:27017


  mongo-express:
    hostname: mongo-express
    container_name: mongmongo-expressodb
    image: mongo-express
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - 27027:8081
    networks:
      - mcc-network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    healthcheck:
      test: wget --quiet --tries=3 --spider http://admin:admin@localhost:8081 || exit 1
      interval: 5s
      timeout: 10s
      retries: 15
    depends_on:
      - mongodb

networks:
  mcc-network:
    name: mcc-network
    driver: bridge

